apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: develop
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: 
            - sh
            - -c
            - |
              MAX_RETRIES=15  
              COUNT=0
              
              until nc -z -w 2 mysql-service 3306; do
                echo "Waiting for mysql..."
                sleep 2
                COUNT=$((COUNT + 1))
                if [ $COUNT -eq $MAX_RETRIES ]; then
                  echo "Tried to connect to mysql $COUNT times, exiting..."
                  exit 1
                fi
              done
              
    
      containers:
        - name: flask
          image: asafnr567/flask-api:2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: flask-config
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            


