apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: develop
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
